

# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
    pmdRunAnalysis: true
    findBugsRunAnalysis: true
    checkStyleRunAnalysis: true
    codeCoverageToolOption: Cobertura
    
- task: CopyFiles@2
  displayName: 'Copy Files to artifact staging directory'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**/target/*.?(war|jar)'
    TargetFolder: $(Build.ArtifactStagingDirectory)

- upload: $(Build.ArtifactStagingDirectory)
  artifact: drop

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.SourcesDirectory)'
  inputs:
    sourceFolder: $(Agent.TempDirectory)
    targetFolder: $(Build.SourcesDirectory)

- script: 'terraform init'
  displayName: 'Terraform init'

- script: 'terraform apply -auto-approve'
  displayName: 'Terraform apply'
    
